version: '3.8'

services:
  psutil_pid_create_json:
    build:
      context: .    # Specify the context directory
      dockerfile: psutil_pid_create_json/Dockerfile  # Specify the Dockerfile to use (if not named 'Dockerfile')
    volumes:
      - data:/data
    environment:
      - PROCESS_FILTER=.*
      - GET_METHOD=psutil
  


  check_pid_json_file:
    build:
      context: .
      dockerfile: check_pid_json_file/Dockerfile
    volumes:
      - data:/data
volumes:
  data:
    driver: local
   

 